language: r
cache: packages
before_install: tlmgr install elsarticle nomencl
script:
- Rscript -e "library(knitr); knit('cartwheel.Rnw', encoding = 'latin1')"
- pdflatex cartwheel.tex
addons:
  artifacts:
    paths: cartwheel.pdf
    s3_region: eu-west-2
deploy:
  provider: s3
  acl: public_read
